### ISSUE TITLE
jsdom is breaking when running this plugin

### ISSUE THREAD

**Issue by jeremyfuksa** [uncss/postcss-uncss#10]
I'm running postcss as part of a Gulp workflow, and when I add this plugin, I get the following error:
```
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (/Users/jf065530/_repos/scouting247/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (/Users/jf065530/_repos/scouting247/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (/Users/jf065530/_repos/scouting247/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
    at Object.M.canvas (https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js:1:3612)
    at https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js:1:8079
    at https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js:1:11064
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at Object.runInContext (vm.js:120:6)
    at processJavaScript (/Users/jf065530/_repos/scouting247/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:190:10)
    at HTMLScriptElementImpl._innerEval (/Users/jf065530/_repos/scouting247/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5) undefined
```
When I comment the uncss plugin out, the workflow runs just fine.

My options follow:
`uncss({
      html: [paths.build + '*.html'],
      ignore: ['.on']
    })`

paths.build is defined. There are HTML files in that directory.

**Comment by RyanZim** [comment]
JSDom unfortunately doesn't support canvas yet. See https://github.com/uncss/uncss/issues/364.
